name: Build
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:  [22, 24, 26]
        react-version: [19]

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set React ${{ matrix.react-version }}
        run:
          npm install
            @types/react@${{ matrix.react-version }}
            @types/react-dom@${{ matrix.react-version }}
            react@${{ matrix.react-version }}
            react-dom@${{ matrix.react-version }}

      - name: Install dependencies
        run: npm install --no-frozen-lockfile

      - run: npm run build

      - run: npm run test
